const shop_data = {
  ternos: {
    id: 1,
    title: 'Ternos',
    routeName: 'ternos',
    items: [
      {
        id: 1,
        name: 'Brown Brim',
        imageUrl: 'https://i.imgur.com/mcEvOpW.jpg',
        price: 25,
      },
      {
        id: 2,
        name: 'Blue Beanie',
        imageUrl: 'https://i.imgur.com/CFg8lNC.jpg',
        price: 18,
      },
      {
        id: 3,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.imgur.com/130ROsP.jpg',
        price: 35,
      },
      {
        id: 4,
        name: 'Grey Brim',
        imageUrl: 'https://i.imgur.com/MZ455Rd.jpg',
        price: 25,
      },
      {
        id: 5,
        name: 'Green Beanie',
        imageUrl: 'https://i.imgur.com/B1zyQvZ.jpg',
        price: 18,
      },
      {
        id: 6,
        name: 'Palm Tree Cap',
        imageUrl: 'https://i.imgur.com/ccunXEo.jpg',
        price: 14,
      },
      {
        id: 7,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/FxmeUDl.jpg',
        price: 18,
      },
      {
        id: 8,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/vUsrsxS.jpg',
        price: 14,
      },
      {
        id: 9,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/d0r2itH.jpg',
        price: 16,
      },
      {
        id: 10,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/w0DvH7l.jpg',
        price: 18,
      },
      {
        id: 11,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/mQ23io4.jpg',
        price: 14,
      },
      {
        id: 12,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/xS1ZeO0.jpg',
        price: 16,
      },
    ],
  },
  sapatos: {
    id: 2,
    title: 'Sapatos',
    routeName: 'sapatos',
    items: [
      {
        id: 13,
        name: 'Brown Brim',
        imageUrl: 'https://i.imgur.com/FByXer5.jpg',
        price: 25,
      },
      {
        id: 14,
        name: 'Blue Beanie',
        imageUrl: 'https://i.imgur.com/bc8pPEl.jpg',
        price: 18,
      },
      {
        id: 15,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.imgur.com/st3KSp3.jpg',
        price: 35,
      },
      {
        id: 16,
        name: 'Grey Brim',
        imageUrl: 'https://i.imgur.com/VtJPmg4.jpg',
        price: 25,
      },
      {
        id: 17,
        name: 'Green Beanie',
        imageUrl: 'https://i.imgur.com/Ai8FLvQ.jpg',
        price: 18,
      },
      {
        id: 18,
        name: 'Palm Tree Cap',
        imageUrl: 'https://i.imgur.com/fZcoLfa.jpg',
        price: 14,
      },
      {
        id: 19,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/LPitD63.jpg',
        price: 18,
      },
      {
        id: 20,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/DKKl80A.jpg',
        price: 14,
      },
      {
        id: 21,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/YIIZQsa.jpg',
        price: 16,
      },
      {
        id: 22,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/6GmQLLL.jpg',
        price: 18,
      },
      {
        id: 23,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/gr3UUVq.jpg',
        price: 14,
      },
      {
        id: 24,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/rXdyIyW.jpg',
        price: 16,
      },
    ],
  },
  relogios: {
    id: 3,
    title: 'Relógios',
    routeName: 'relogios',
    items: [
      {
        id: 25,
        name: 'Brown Brim',
        imageUrl: 'https://i.imgur.com/V6umOhz.jpg',
        price: 25,
      },
      {
        id: 26,
        name: 'Blue Beanie',
        imageUrl: 'https://i.imgur.com/BT81vXo.jpg',
        price: 18,
      },
      {
        id: 27,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.imgur.com/9dutQ0v.jpg',
        price: 35,
      },
      {
        id: 28,
        name: 'Grey Brim',
        imageUrl: 'https://i.imgur.com/l0Afiak.jpg',
        price: 25,
      },
      {
        id: 29,
        name: 'Green Beanie',
        imageUrl: 'https://i.imgur.com/2Mx8DsU.jpg',
        price: 18,
      },
      {
        id: 30,
        name: 'Palm Tree Cap',
        imageUrl: 'https://i.imgur.com/jx9TUHR.jpg',
        price: 14,
      },
      {
        id: 31,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/EE7Is69.jpg',
        price: 18,
      },
      {
        id: 32,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/OQssPmd.jpg',
        price: 14,
      },
      {
        id: 33,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/F3cb7YR.jpg',
        price: 16,
      },
      {
        id: 34,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/tW0z0tJ.jpg',
        price: 18,
      },
      {
        id: 35,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/Rpbqbso.jpg',
        price: 14,
      },
      {
        id: 36,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/cmdhbht.jpg',
        price: 16,
      },
    ],
  },
  calcas: {
    id: 4,
    title: 'Calças',
    routeName: 'calcas',
    items: [
      {
        id: 37,
        name: 'Brown Brim',
        imageUrl: 'https://i.imgur.com/z6ztpO8.jpg',
        price: 25,
      },
      {
        id: 38,
        name: 'Blue Beanie',
        imageUrl: 'https://i.imgur.com/B7MfN1V.jpg',
        price: 18,
      },
      {
        id: 39,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.imgur.com/iQuJsDV.jpg',
        price: 35,
      },
      {
        id: 40,
        name: 'Grey Brim',
        imageUrl: 'https://i.imgur.com/A7FEL9Y.jpg',
        price: 25,
      },
      {
        id: 41,
        name: 'Green Beanie',
        imageUrl: 'https://i.imgur.com/r7tEudl.jpg',
        price: 18,
      },
      {
        id: 42,
        name: 'Palm Tree Cap',
        imageUrl: 'https://i.imgur.com/pGXTyLm.jpg',
        price: 14,
      },
      {
        id: 43,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/6IBpiYy.jpg',
        price: 18,
      },
      {
        id: 44,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/Mncx6mf.jpg',
        price: 14,
      },
      {
        id: 45,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/1E4nkEv.jpg',
        price: 16,
      },
      {
        id: 46,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/ynpOoOH.jpg',
        price: 18,
      },
      {
        id: 47,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/MJZA8Xi.jpg',
        price: 14,
      },
      {
        id: 48,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/cO7FQVY.jpg',
        price: 16,
      },
    ],
  },
  camisas: {
    id: 4,
    title: 'Camisas',
    routeName: 'camisas',
    items: [
      {
        id: 49,
        name: 'Brown Brim',
        imageUrl: 'https://i.imgur.com/GLrosrj.jpg',
        price: 25,
      },
      {
        id: 50,
        name: 'Blue Beanie',
        imageUrl: 'https://i.imgur.com/kdVEySy.jpg',
        price: 18,
      },
      {
        id: 51,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.imgur.com/QY5htAO.jpg',
        price: 35,
      },
      {
        id: 52,
        name: 'Grey Brim',
        imageUrl: 'https://i.imgur.com/I45802m.jpg',
        price: 25,
      },
      {
        id: 53,
        name: 'Green Beanie',
        imageUrl: 'https://i.imgur.com/6lFOo2F.jpg',
        price: 18,
      },
      {
        id: 54,
        name: 'Palm Tree Cap',
        imageUrl: 'https://i.imgur.com/YxYQL9H.jpg',
        price: 14,
      },
      {
        id: 55,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/pgYswgA.jpg',
        price: 18,
      },
      {
        id: 56,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/rFT2hAK.jpg',
        price: 14,
      },
      {
        id: 57,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/3uxt137.jpg',
        price: 16,
      },
      {
        id: 58,
        name: 'Red Beanie',
        imageUrl: 'https://i.imgur.com/GtBue1P.jpg',
        price: 18,
      },
      {
        id: 59,
        name: 'Wolf Cap',
        imageUrl: 'https://i.imgur.com/ZimPmG9.jpg',
        price: 14,
      },
      {
        id: 60,
        name: 'Blue Snapback',
        imageUrl: 'https://i.imgur.com/3hiTD3G.jpg',
        price: 16,
      },
    ],
  },
};

export default shop_data;
