const shop_data = {
  ternos: {
    id: 1,
    title: 'Ternos',
    routeName: 'ternos',
    items: [
      {
        id: 1,
        name: 'Terno azul slim',
        imageUrl: 'https://i.imgur.com/mcEvOpW.jpg',
        price: 185,
      },
      {
        id: 2,
        name: 'Terno de linho',
        imageUrl: 'https://i.imgur.com/CFg8lNC.jpg',
        price: 198,
      },
      {
        id: 3,
        name: 'Terno roxo slim',
        imageUrl: 'https://i.imgur.com/130ROsP.jpg',
        price: 185,
      },
      {
        id: 4,
        name: 'Terno de lã',
        imageUrl: 'https://i.imgur.com/MZ455Rd.jpg',
        price: 177,
      },
      {
        id: 5,
        name: 'Terno azul royal',
        imageUrl: 'https://i.imgur.com/B1zyQvZ.jpg',
        price: 199,
      },
      {
        id: 6,
        name: 'Terno clássico slim',
        imageUrl: 'https://i.imgur.com/ccunXEo.jpg',
        price: 148,
      },
      {
        id: 7,
        name: 'Terno de linho slim',
        imageUrl: 'https://i.imgur.com/FxmeUDl.jpg',
        price: 189,
      },
      {
        id: 8,
        name: 'Terno de lã estruturado',
        imageUrl: 'https://i.imgur.com/vUsrsxS.jpg',
        price: 188,
      },
      {
        id: 9,
        name: 'Terno slim azul',
        imageUrl: 'https://i.imgur.com/d0r2itH.jpg',
        price: 169,
      },
      {
        id: 10,
        name: 'Terno de linho slim',
        imageUrl: 'https://i.imgur.com/w0DvH7l.jpg',
        price: 186,
      },
      {
        id: 11,
        name: 'Terno slim estruturado',
        imageUrl: 'https://i.imgur.com/mQ23io4.jpg',
        price: 185,
      },
      {
        id: 12,
        name: 'Terno cinzento em linho',
        imageUrl: 'https://i.imgur.com/xS1ZeO0.jpg',
        price: 169,
      },
    ],
  },
  sapatos: {
    id: 2,
    title: 'Sapatos',
    routeName: 'sapatos',
    items: [
      {
        id: 13,
        name: 'Mocassim em pele',
        imageUrl: 'https://i.imgur.com/FByXer5.jpg',
        price: 259,
      },
      {
        id: 14,
        name: 'Tênis casual preto',
        imageUrl: 'https://i.imgur.com/bc8pPEl.jpg',
        price: 187,
      },
      {
        id: 15,
        name: 'Botins pretas',
        imageUrl: 'https://i.imgur.com/st3KSp3.jpg',
        price: 352,
      },
      {
        id: 16,
        name: 'Botins em pele',
        imageUrl: 'https://i.imgur.com/VtJPmg4.jpg',
        price: 255,
      },
      {
        id: 17,
        name: 'Mocassim marrom',
        imageUrl: 'https://i.imgur.com/Ai8FLvQ.jpg',
        price: 187,
      },
      {
        id: 18,
        name: 'Botins em couro',
        imageUrl: 'https://i.imgur.com/fZcoLfa.jpg',
        price: 144,
      },
      {
        id: 19,
        name: 'Mocassim em pele',
        imageUrl: 'https://i.imgur.com/LPitD63.jpg',
        price: 186,
      },
      {
        id: 20,
        name: 'Tênis azul',
        imageUrl: 'https://i.imgur.com/DKKl80A.jpg',
        price: 142,
      },
      {
        id: 21,
        name: 'Botins em couro',
        imageUrl: 'https://i.imgur.com/YIIZQsa.jpg',
        price: 169,
      },
      {
        id: 22,
        name: 'Sapato em pele marrom',
        imageUrl: 'https://i.imgur.com/6GmQLLL.jpg',
        price: 181,
      },
      {
        id: 23,
        name: 'Botins em pele marrom',
        imageUrl: 'https://i.imgur.com/gr3UUVq.jpg',
        price: 144,
      },
      {
        id: 24,
        name: 'Tênis em couro',
        imageUrl: 'https://i.imgur.com/rXdyIyW.jpg',
        price: 167,
      },
    ],
  },
  relogios: {
    id: 3,
    title: 'Relógios',
    routeName: 'relogios',
    items: [
      {
        id: 25,
        name: 'Relógio Maserati',
        imageUrl: 'https://i.imgur.com/V6umOhz.jpg',
        price: 259,
      },
      {
        id: 26,
        name: 'Relógio Swatch',
        imageUrl: 'https://i.imgur.com/BT81vXo.jpg',
        price: 256,
      },
      {
        id: 27,
        name: 'Relógio Stone',
        imageUrl: 'https://i.imgur.com/9dutQ0v.jpg',
        price: 355,
      },
      {
        id: 28,
        name: 'Relógio Astar',
        imageUrl: 'https://i.imgur.com/l0Afiak.jpg',
        price: 259,
      },
      {
        id: 29,
        name: 'Relógio Swatch',
        imageUrl: 'https://i.imgur.com/2Mx8DsU.jpg',
        price: 288,
      },
      {
        id: 30,
        name: 'Relógio Timberland',
        imageUrl: 'https://i.imgur.com/jx9TUHR.jpg',
        price: 366,
      },
      {
        id: 31,
        name: 'Relógio Maserati',
        imageUrl: 'https://i.imgur.com/EE7Is69.jpg',
        price: 359,
      },
      {
        id: 32,
        name: 'Relógio Stone',
        imageUrl: 'https://i.imgur.com/OQssPmd.jpg',
        price: 295,
      },
      {
        id: 33,
        name: 'Relógio Timberland',
        imageUrl: 'https://i.imgur.com/F3cb7YR.jpg',
        price: 288,
      },
      {
        id: 34,
        name: 'Relógio Astar',
        imageUrl: 'https://i.imgur.com/tW0z0tJ.jpg',
        price: 366,
      },
      {
        id: 35,
        name: 'Relógio Maserati',
        imageUrl: 'https://i.imgur.com/Rpbqbso.jpg',
        price: 369,
      },
      {
        id: 36,
        name: 'Relógio Swatch',
        imageUrl: 'https://i.imgur.com/cmdhbht.jpg',
        price: 296,
      },
    ],
  },
  calcas: {
    id: 4,
    title: 'Calças',
    routeName: 'calcas',
    items: [
      {
        id: 37,
        name: 'Calças retas em linho',
        imageUrl: 'https://i.imgur.com/z6ztpO8.jpg',
        price: 155,
      },
      {
        id: 38,
        name: 'Calças chino em algodão',
        imageUrl: 'https://i.imgur.com/B7MfN1V.jpg',
        price: 188,
      },
      {
        id: 39,
        name: 'Calças slim em linho',
        imageUrl: 'https://i.imgur.com/iQuJsDV.jpg',
        price: 147,
      },
      {
        id: 40,
        name: 'Calças retas em brim',
        imageUrl: 'https://i.imgur.com/A7FEL9Y.jpg',
        price: 129,
      },
      {
        id: 41,
        name: 'Calças chino em sarja',
        imageUrl: 'https://i.imgur.com/r7tEudl.jpg',
        price: 187,
      },
      {
        id: 42,
        name: 'Calças skinny fit',
        imageUrl: 'https://i.imgur.com/pGXTyLm.jpg',
        price: 145,
      },
      {
        id: 43,
        name: 'Calças slim em algodão',
        imageUrl: 'https://i.imgur.com/6IBpiYy.jpg',
        price: 189,
      },
      {
        id: 44,
        name: 'Calças chino em linho',
        imageUrl: 'https://i.imgur.com/Mncx6mf.jpg',
        price: 145,
      },
      {
        id: 45,
        name: 'Calças skinny',
        imageUrl: 'https://i.imgur.com/1E4nkEv.jpg',
        price: 165,
      },
      {
        id: 46,
        name: 'Calças retas em algodão',
        imageUrl: 'https://i.imgur.com/ynpOoOH.jpg',
        price: 187,
      },
      {
        id: 47,
        name: 'Calça slim fit',
        imageUrl: 'https://i.imgur.com/MJZA8Xi.jpg',
        price: 148,
      },
      {
        id: 48,
        name: 'Calças retas em sarja',
        imageUrl: 'https://i.imgur.com/cO7FQVY.jpg',
        price: 169,
      },
    ],
  },
  camisas: {
    id: 4,
    title: 'Camisas',
    routeName: 'camisas',
    items: [
      {
        id: 49,
        name: 'Camisa relaxed listras',
        imageUrl: 'https://i.imgur.com/GLrosrj.jpg',
        price: 142,
      },
      {
        id: 50,
        name: 'Camisa slim cinza',
        imageUrl: 'https://i.imgur.com/kdVEySy.jpg',
        price: 119,
      },
      {
        id: 51,
        name: 'Camisa large fit',
        imageUrl: 'https://i.imgur.com/QY5htAO.jpg',
        price: 129,
      },
      {
        id: 52,
        name: 'Camisa slim xadrez',
        imageUrl: 'https://i.imgur.com/I45802m.jpg',
        price: 134,
      },
      {
        id: 53,
        name: 'Camisa slim basic',
        imageUrl: 'https://i.imgur.com/6lFOo2F.jpg',
        price: 152,
      },
      {
        id: 54,
        name: 'Camisa sport listras',
        imageUrl: 'https://i.imgur.com/YxYQL9H.jpg',
        price: 147,
      },
      {
        id: 55,
        name: 'Camisa relaxed xadrez',
        imageUrl: 'https://i.imgur.com/pgYswgA.jpg',
        price: 112,
      },
      {
        id: 56,
        name: 'Camisa slim summer',
        imageUrl: 'https://i.imgur.com/rFT2hAK.jpg',
        price: 145,
      },
      {
        id: 57,
        name: 'Camisa regular fit',
        imageUrl: 'https://i.imgur.com/3uxt137.jpg',
        price: 161,
      },
      {
        id: 58,
        name: 'Camisa relaxed mostarda',
        imageUrl: 'https://i.imgur.com/GtBue1P.jpg',
        price: 128,
      },
      {
        id: 59,
        name: 'camisa basic azul',
        imageUrl: 'https://i.imgur.com/ZimPmG9.jpg',
        price: 141,
      },
      {
        id: 60,
        name: 'Camisa relaxed xadrez',
        imageUrl: 'https://i.imgur.com/3hiTD3G.jpg',
        price: 136,
      },
    ],
  },
};

export default shop_data;
